'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8762
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.8762.
'
Namespace ir.smsapp
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="v2Soap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class v2
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private SendSMSOperationCompleted As System.Threading.SendOrPostCallback
        
        Private SendSMS2OperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetMessageStatusOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetCreditOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CheckMessageIDsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetReceiveMessagesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetCountForPostalCodeOperationCompleted As System.Threading.SendOrPostCallback
        
        Private SendBulkSmsToPostalCodeOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetBulkRequestInfoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetNewsListOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CancelOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetPaymentUrlOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.W_ISM.My.MySettings.Default.W_ISM_ir_smsapp_v2
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event SendSMSCompleted As SendSMSCompletedEventHandler
        
        '''<remarks/>
        Public Event SendSMS2Completed As SendSMS2CompletedEventHandler
        
        '''<remarks/>
        Public Event GetMessageStatusCompleted As GetMessageStatusCompletedEventHandler
        
        '''<remarks/>
        Public Event GetCreditCompleted As GetCreditCompletedEventHandler
        
        '''<remarks/>
        Public Event CheckMessageIDsCompleted As CheckMessageIDsCompletedEventHandler
        
        '''<remarks/>
        Public Event GetReceiveMessagesCompleted As GetReceiveMessagesCompletedEventHandler
        
        '''<remarks/>
        Public Event GetCountForPostalCodeCompleted As GetCountForPostalCodeCompletedEventHandler
        
        '''<remarks/>
        Public Event SendBulkSmsToPostalCodeCompleted As SendBulkSmsToPostalCodeCompletedEventHandler
        
        '''<remarks/>
        Public Event GetBulkRequestInfoCompleted As GetBulkRequestInfoCompletedEventHandler
        
        '''<remarks/>
        Public Event GetNewsListCompleted As GetNewsListCompletedEventHandler
        
        '''<remarks/>
        Public Event CancelCompleted As CancelCompletedEventHandler
        
        '''<remarks/>
        Public Event GetPaymentUrlCompleted As GetPaymentUrlCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendSMS", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SendSMS(ByVal username As String, ByVal password As String, ByVal senderNumbers() As String, ByVal recipientNumbers() As String, ByVal messageBodies() As String, ByVal sendDate() As String, ByVal messageClasses() As Integer, ByVal checkingMessageIds() As Long) As Long()
            Dim results() As Object = Me.Invoke("SendSMS", New Object() {username, password, senderNumbers, recipientNumbers, messageBodies, sendDate, messageClasses, checkingMessageIds})
            Return CType(results(0),Long())
        End Function
        
        '''<remarks/>
        Public Overloads Sub SendSMSAsync(ByVal username As String, ByVal password As String, ByVal senderNumbers() As String, ByVal recipientNumbers() As String, ByVal messageBodies() As String, ByVal sendDate() As String, ByVal messageClasses() As Integer, ByVal checkingMessageIds() As Long)
            Me.SendSMSAsync(username, password, senderNumbers, recipientNumbers, messageBodies, sendDate, messageClasses, checkingMessageIds, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SendSMSAsync(ByVal username As String, ByVal password As String, ByVal senderNumbers() As String, ByVal recipientNumbers() As String, ByVal messageBodies() As String, ByVal sendDate() As String, ByVal messageClasses() As Integer, ByVal checkingMessageIds() As Long, ByVal userState As Object)
            If (Me.SendSMSOperationCompleted Is Nothing) Then
                Me.SendSMSOperationCompleted = AddressOf Me.OnSendSMSOperationCompleted
            End If
            Me.InvokeAsync("SendSMS", New Object() {username, password, senderNumbers, recipientNumbers, messageBodies, sendDate, messageClasses, checkingMessageIds}, Me.SendSMSOperationCompleted, userState)
        End Sub
        
        Private Sub OnSendSMSOperationCompleted(ByVal arg As Object)
            If (Not (Me.SendSMSCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SendSMSCompleted(Me, New SendSMSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendSMS2", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SendSMS2(ByVal username As String, ByVal password As String, ByVal senderNumbers As String, ByVal recipientNumbers() As String, ByVal messageBodies As String, ByVal sendDate As String, ByVal messageClasses As Integer, ByVal checkingMessageIds() As Long) As Long()
            Dim results() As Object = Me.Invoke("SendSMS2", New Object() {username, password, senderNumbers, recipientNumbers, messageBodies, sendDate, messageClasses, checkingMessageIds})
            Return CType(results(0),Long())
        End Function
        
        '''<remarks/>
        Public Overloads Sub SendSMS2Async(ByVal username As String, ByVal password As String, ByVal senderNumbers As String, ByVal recipientNumbers() As String, ByVal messageBodies As String, ByVal sendDate As String, ByVal messageClasses As Integer, ByVal checkingMessageIds() As Long)
            Me.SendSMS2Async(username, password, senderNumbers, recipientNumbers, messageBodies, sendDate, messageClasses, checkingMessageIds, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SendSMS2Async(ByVal username As String, ByVal password As String, ByVal senderNumbers As String, ByVal recipientNumbers() As String, ByVal messageBodies As String, ByVal sendDate As String, ByVal messageClasses As Integer, ByVal checkingMessageIds() As Long, ByVal userState As Object)
            If (Me.SendSMS2OperationCompleted Is Nothing) Then
                Me.SendSMS2OperationCompleted = AddressOf Me.OnSendSMS2OperationCompleted
            End If
            Me.InvokeAsync("SendSMS2", New Object() {username, password, senderNumbers, recipientNumbers, messageBodies, sendDate, messageClasses, checkingMessageIds}, Me.SendSMS2OperationCompleted, userState)
        End Sub
        
        Private Sub OnSendSMS2OperationCompleted(ByVal arg As Object)
            If (Not (Me.SendSMS2CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SendSMS2Completed(Me, New SendSMS2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMessageStatus", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetMessageStatus(ByVal username As String, ByVal password As String, ByVal MessageIDs() As Long) As Integer()
            Dim results() As Object = Me.Invoke("GetMessageStatus", New Object() {username, password, MessageIDs})
            Return CType(results(0),Integer())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetMessageStatusAsync(ByVal username As String, ByVal password As String, ByVal MessageIDs() As Long)
            Me.GetMessageStatusAsync(username, password, MessageIDs, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetMessageStatusAsync(ByVal username As String, ByVal password As String, ByVal MessageIDs() As Long, ByVal userState As Object)
            If (Me.GetMessageStatusOperationCompleted Is Nothing) Then
                Me.GetMessageStatusOperationCompleted = AddressOf Me.OnGetMessageStatusOperationCompleted
            End If
            Me.InvokeAsync("GetMessageStatus", New Object() {username, password, MessageIDs}, Me.GetMessageStatusOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetMessageStatusOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetMessageStatusCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetMessageStatusCompleted(Me, New GetMessageStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCredit", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetCredit(ByVal username As String, ByVal password As String) As Double
            Dim results() As Object = Me.Invoke("GetCredit", New Object() {username, password})
            Return CType(results(0),Double)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetCreditAsync(ByVal username As String, ByVal password As String)
            Me.GetCreditAsync(username, password, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetCreditAsync(ByVal username As String, ByVal password As String, ByVal userState As Object)
            If (Me.GetCreditOperationCompleted Is Nothing) Then
                Me.GetCreditOperationCompleted = AddressOf Me.OnGetCreditOperationCompleted
            End If
            Me.InvokeAsync("GetCredit", New Object() {username, password}, Me.GetCreditOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetCreditOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetCreditCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetCreditCompleted(Me, New GetCreditCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckMessageIDs", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CheckMessageIDs(ByVal username As String, ByVal password As String, ByVal checkingids() As Long) As Long()
            Dim results() As Object = Me.Invoke("CheckMessageIDs", New Object() {username, password, checkingids})
            Return CType(results(0),Long())
        End Function
        
        '''<remarks/>
        Public Overloads Sub CheckMessageIDsAsync(ByVal username As String, ByVal password As String, ByVal checkingids() As Long)
            Me.CheckMessageIDsAsync(username, password, checkingids, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CheckMessageIDsAsync(ByVal username As String, ByVal password As String, ByVal checkingids() As Long, ByVal userState As Object)
            If (Me.CheckMessageIDsOperationCompleted Is Nothing) Then
                Me.CheckMessageIDsOperationCompleted = AddressOf Me.OnCheckMessageIDsOperationCompleted
            End If
            Me.InvokeAsync("CheckMessageIDs", New Object() {username, password, checkingids}, Me.CheckMessageIDsOperationCompleted, userState)
        End Sub
        
        Private Sub OnCheckMessageIDsOperationCompleted(ByVal arg As Object)
            If (Not (Me.CheckMessageIDsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CheckMessageIDsCompleted(Me, New CheckMessageIDsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetReceiveMessages", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetReceiveMessages(ByVal username As String, ByVal password As String, ByVal destNumber As String, ByVal isRead As Integer) As Messages()
            Dim results() As Object = Me.Invoke("GetReceiveMessages", New Object() {username, password, destNumber, isRead})
            Return CType(results(0),Messages())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetReceiveMessagesAsync(ByVal username As String, ByVal password As String, ByVal destNumber As String, ByVal isRead As Integer)
            Me.GetReceiveMessagesAsync(username, password, destNumber, isRead, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetReceiveMessagesAsync(ByVal username As String, ByVal password As String, ByVal destNumber As String, ByVal isRead As Integer, ByVal userState As Object)
            If (Me.GetReceiveMessagesOperationCompleted Is Nothing) Then
                Me.GetReceiveMessagesOperationCompleted = AddressOf Me.OnGetReceiveMessagesOperationCompleted
            End If
            Me.InvokeAsync("GetReceiveMessages", New Object() {username, password, destNumber, isRead}, Me.GetReceiveMessagesOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetReceiveMessagesOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetReceiveMessagesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetReceiveMessagesCompleted(Me, New GetReceiveMessagesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCountForPostalCode", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetCountForPostalCode(ByVal username As String, ByVal password As String, ByVal postalcode As String) As Integer
            Dim results() As Object = Me.Invoke("GetCountForPostalCode", New Object() {username, password, postalcode})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetCountForPostalCodeAsync(ByVal username As String, ByVal password As String, ByVal postalcode As String)
            Me.GetCountForPostalCodeAsync(username, password, postalcode, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetCountForPostalCodeAsync(ByVal username As String, ByVal password As String, ByVal postalcode As String, ByVal userState As Object)
            If (Me.GetCountForPostalCodeOperationCompleted Is Nothing) Then
                Me.GetCountForPostalCodeOperationCompleted = AddressOf Me.OnGetCountForPostalCodeOperationCompleted
            End If
            Me.InvokeAsync("GetCountForPostalCode", New Object() {username, password, postalcode}, Me.GetCountForPostalCodeOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetCountForPostalCodeOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetCountForPostalCodeCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetCountForPostalCodeCompleted(Me, New GetCountForPostalCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendBulkSmsToPostalCode", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SendBulkSmsToPostalCode(ByVal username As String, ByVal password As String, ByVal postalcode As String, ByVal originator As String, ByVal content As String, ByVal sendType As SendType, ByVal sendDate As Date, ByVal startIndex As Integer, ByVal count As Integer) As Long
            Dim results() As Object = Me.Invoke("SendBulkSmsToPostalCode", New Object() {username, password, postalcode, originator, content, sendType, sendDate, startIndex, count})
            Return CType(results(0),Long)
        End Function
        
        '''<remarks/>
        Public Overloads Sub SendBulkSmsToPostalCodeAsync(ByVal username As String, ByVal password As String, ByVal postalcode As String, ByVal originator As String, ByVal content As String, ByVal sendType As SendType, ByVal sendDate As Date, ByVal startIndex As Integer, ByVal count As Integer)
            Me.SendBulkSmsToPostalCodeAsync(username, password, postalcode, originator, content, sendType, sendDate, startIndex, count, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SendBulkSmsToPostalCodeAsync(ByVal username As String, ByVal password As String, ByVal postalcode As String, ByVal originator As String, ByVal content As String, ByVal sendType As SendType, ByVal sendDate As Date, ByVal startIndex As Integer, ByVal count As Integer, ByVal userState As Object)
            If (Me.SendBulkSmsToPostalCodeOperationCompleted Is Nothing) Then
                Me.SendBulkSmsToPostalCodeOperationCompleted = AddressOf Me.OnSendBulkSmsToPostalCodeOperationCompleted
            End If
            Me.InvokeAsync("SendBulkSmsToPostalCode", New Object() {username, password, postalcode, originator, content, sendType, sendDate, startIndex, count}, Me.SendBulkSmsToPostalCodeOperationCompleted, userState)
        End Sub
        
        Private Sub OnSendBulkSmsToPostalCodeOperationCompleted(ByVal arg As Object)
            If (Not (Me.SendBulkSmsToPostalCodeCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SendBulkSmsToPostalCodeCompleted(Me, New SendBulkSmsToPostalCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetBulkRequestInfo", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetBulkRequestInfo(ByVal username As String, ByVal password As String, ByVal requestId As Long) As RequestInfo
            Dim results() As Object = Me.Invoke("GetBulkRequestInfo", New Object() {username, password, requestId})
            Return CType(results(0),RequestInfo)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetBulkRequestInfoAsync(ByVal username As String, ByVal password As String, ByVal requestId As Long)
            Me.GetBulkRequestInfoAsync(username, password, requestId, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetBulkRequestInfoAsync(ByVal username As String, ByVal password As String, ByVal requestId As Long, ByVal userState As Object)
            If (Me.GetBulkRequestInfoOperationCompleted Is Nothing) Then
                Me.GetBulkRequestInfoOperationCompleted = AddressOf Me.OnGetBulkRequestInfoOperationCompleted
            End If
            Me.InvokeAsync("GetBulkRequestInfo", New Object() {username, password, requestId}, Me.GetBulkRequestInfoOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetBulkRequestInfoOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetBulkRequestInfoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetBulkRequestInfoCompleted(Me, New GetBulkRequestInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetNewsList", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetNewsList(ByVal username As String, ByVal password As String) As News()
            Dim results() As Object = Me.Invoke("GetNewsList", New Object() {username, password})
            Return CType(results(0),News())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetNewsListAsync(ByVal username As String, ByVal password As String)
            Me.GetNewsListAsync(username, password, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetNewsListAsync(ByVal username As String, ByVal password As String, ByVal userState As Object)
            If (Me.GetNewsListOperationCompleted Is Nothing) Then
                Me.GetNewsListOperationCompleted = AddressOf Me.OnGetNewsListOperationCompleted
            End If
            Me.InvokeAsync("GetNewsList", New Object() {username, password}, Me.GetNewsListOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetNewsListOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetNewsListCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetNewsListCompleted(Me, New GetNewsListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Cancel", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Cancel(ByVal username As String, ByVal password As String, ByVal MessageIDs() As Long) As Integer()
            Dim results() As Object = Me.Invoke("Cancel", New Object() {username, password, MessageIDs})
            Return CType(results(0),Integer())
        End Function
        
        '''<remarks/>
        Public Overloads Sub CancelAsync(ByVal username As String, ByVal password As String, ByVal MessageIDs() As Long)
            Me.CancelAsync(username, password, MessageIDs, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CancelAsync(ByVal username As String, ByVal password As String, ByVal MessageIDs() As Long, ByVal userState As Object)
            If (Me.CancelOperationCompleted Is Nothing) Then
                Me.CancelOperationCompleted = AddressOf Me.OnCancelOperationCompleted
            End If
            Me.InvokeAsync("Cancel", New Object() {username, password, MessageIDs}, Me.CancelOperationCompleted, userState)
        End Sub
        
        Private Sub OnCancelOperationCompleted(ByVal arg As Object)
            If (Not (Me.CancelCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CancelCompleted(Me, New CancelCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPaymentUrl", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetPaymentUrl(ByVal username As String, ByVal price As Integer) As String
            Dim results() As Object = Me.Invoke("GetPaymentUrl", New Object() {username, price})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetPaymentUrlAsync(ByVal username As String, ByVal price As Integer)
            Me.GetPaymentUrlAsync(username, price, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetPaymentUrlAsync(ByVal username As String, ByVal price As Integer, ByVal userState As Object)
            If (Me.GetPaymentUrlOperationCompleted Is Nothing) Then
                Me.GetPaymentUrlOperationCompleted = AddressOf Me.OnGetPaymentUrlOperationCompleted
            End If
            Me.InvokeAsync("GetPaymentUrl", New Object() {username, price}, Me.GetPaymentUrlOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetPaymentUrlOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetPaymentUrlCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetPaymentUrlCompleted(Me, New GetPaymentUrlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Sub CancelAsync1(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5494"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Messages
        
        Private messageIDField As Long
        
        Private recipientNumberField As String
        
        Private senderNumberField As String
        
        Private bodyField As String
        
        Private receiveDateField As String
        
        '''<remarks/>
        Public Property MessageID() As Long
            Get
                Return Me.messageIDField
            End Get
            Set
                Me.messageIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RecipientNumber() As String
            Get
                Return Me.recipientNumberField
            End Get
            Set
                Me.recipientNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SenderNumber() As String
            Get
                Return Me.senderNumberField
            End Get
            Set
                Me.senderNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Body() As String
            Get
                Return Me.bodyField
            End Get
            Set
                Me.bodyField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ReceiveDate() As String
            Get
                Return Me.receiveDateField
            End Get
            Set
                Me.receiveDateField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5494"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class News
        
        Private idField As Integer
        
        Private textField As String
        
        Private postDateField As Date
        
        Private targetField As Integer
        
        Private postTypeField As Integer
        
        Private subjectField As String
        
        Private byResellerIdField As Integer
        
        Private userIdField As Integer
        
        Private expireDateField As Date
        
        Private priorityField As Integer
        
        '''<remarks/>
        Public Property Id() As Integer
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Text() As String
            Get
                Return Me.textField
            End Get
            Set
                Me.textField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PostDate() As Date
            Get
                Return Me.postDateField
            End Get
            Set
                Me.postDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Target() As Integer
            Get
                Return Me.targetField
            End Get
            Set
                Me.targetField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PostType() As Integer
            Get
                Return Me.postTypeField
            End Get
            Set
                Me.postTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Subject() As String
            Get
                Return Me.subjectField
            End Get
            Set
                Me.subjectField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ByResellerId() As Integer
            Get
                Return Me.byResellerIdField
            End Get
            Set
                Me.byResellerIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UserId() As Integer
            Get
                Return Me.userIdField
            End Get
            Set
                Me.userIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ExpireDate() As Date
            Get
                Return Me.expireDateField
            End Get
            Set
                Me.expireDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Priority() As Integer
            Get
                Return Me.priorityField
            End Get
            Set
                Me.priorityField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5494"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class RequestDelivery
        
        Private statusIdField As Long
        
        Private statusCountField As Long
        
        '''<remarks/>
        Public Property statusId() As Long
            Get
                Return Me.statusIdField
            End Get
            Set
                Me.statusIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property statusCount() As Long
            Get
                Return Me.statusCountField
            End Get
            Set
                Me.statusCountField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5494"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class RequestInfo
        
        Private idField As Long
        
        Private senderNumberField As String
        
        Private messageField As String
        
        Private sendDateField As Date
        
        Private totalSmsField As Integer
        
        Private priceField As Integer
        
        Private statusField As Integer
        
        Private statusDescriptionField As String
        
        Private deliveryReportField() As RequestDelivery
        
        '''<remarks/>
        Public Property id() As Long
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property senderNumber() As String
            Get
                Return Me.senderNumberField
            End Get
            Set
                Me.senderNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property message() As String
            Get
                Return Me.messageField
            End Get
            Set
                Me.messageField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property sendDate() As Date
            Get
                Return Me.sendDateField
            End Get
            Set
                Me.sendDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property totalSms() As Integer
            Get
                Return Me.totalSmsField
            End Get
            Set
                Me.totalSmsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property price() As Integer
            Get
                Return Me.priceField
            End Get
            Set
                Me.priceField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property status() As Integer
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property statusDescription() As String
            Get
                Return Me.statusDescriptionField
            End Get
            Set
                Me.statusDescriptionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property deliveryReport() As RequestDelivery()
            Get
                Return Me.deliveryReportField
            End Get
            Set
                Me.deliveryReportField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5494"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Public Enum SendType
        
        '''<remarks/>
        AllNumbers
        
        '''<remarks/>
        RandomNumbers
        
        '''<remarks/>
        SortingNumbers
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")>  _
    Public Delegate Sub SendSMSCompletedEventHandler(ByVal sender As Object, ByVal e As SendSMSCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SendSMSCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Long()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Long())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")>  _
    Public Delegate Sub SendSMS2CompletedEventHandler(ByVal sender As Object, ByVal e As SendSMS2CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SendSMS2CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Long()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Long())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")>  _
    Public Delegate Sub GetMessageStatusCompletedEventHandler(ByVal sender As Object, ByVal e As GetMessageStatusCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetMessageStatusCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")>  _
    Public Delegate Sub GetCreditCompletedEventHandler(ByVal sender As Object, ByVal e As GetCreditCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetCreditCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Double
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Double)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")>  _
    Public Delegate Sub CheckMessageIDsCompletedEventHandler(ByVal sender As Object, ByVal e As CheckMessageIDsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CheckMessageIDsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Long()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Long())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")>  _
    Public Delegate Sub GetReceiveMessagesCompletedEventHandler(ByVal sender As Object, ByVal e As GetReceiveMessagesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetReceiveMessagesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Messages()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Messages())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")>  _
    Public Delegate Sub GetCountForPostalCodeCompletedEventHandler(ByVal sender As Object, ByVal e As GetCountForPostalCodeCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetCountForPostalCodeCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")>  _
    Public Delegate Sub SendBulkSmsToPostalCodeCompletedEventHandler(ByVal sender As Object, ByVal e As SendBulkSmsToPostalCodeCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SendBulkSmsToPostalCodeCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Long
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Long)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")>  _
    Public Delegate Sub GetBulkRequestInfoCompletedEventHandler(ByVal sender As Object, ByVal e As GetBulkRequestInfoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetBulkRequestInfoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RequestInfo
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RequestInfo)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")>  _
    Public Delegate Sub GetNewsListCompletedEventHandler(ByVal sender As Object, ByVal e As GetNewsListCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetNewsListCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As News()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),News())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")>  _
    Public Delegate Sub CancelCompletedEventHandler(ByVal sender As Object, ByVal e As CancelCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CancelCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")>  _
    Public Delegate Sub GetPaymentUrlCompletedEventHandler(ByVal sender As Object, ByVal e As GetPaymentUrlCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetPaymentUrlCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
